import { Utils } from "electrobun/bun";
import { homedir, tmpdir } from "os";
import { join } from "path";

export const OPENROUTER_KEYCHAIN_SERVICE = "com.buddywriter.openrouter";
export const OPENROUTER_KEYCHAIN_ACCOUNT = "default";
export const MAX_SIDECAR_LOG_LINES = 80;
export const LOCAL_AI_REMOTE_CATALOG_URL = Bun.env.BUDDYWRITER_LOCAL_AI_CATALOG_URL?.trim() ?? "";
export const UV_INSTALL_SCRIPT_URL = "https://astral.sh/uv/install.sh";
export const DEFAULT_UV_PYTHON = "3.12.7";
export const MLX_PORT = 8079;
export const GRAMMAR_PORT = 8080;
export const STT_PORT = 8765;
export const TTS_PORT = 8766;
export const TEXT_SIDECAR_IDLE_MS = 3 * 60_000;
export const GRAMMAR_SIDECAR_IDLE_MS = 3 * 60_000;
export const STT_SIDECAR_IDLE_MS = 60_000;
export const TTS_SIDECAR_IDLE_MS = 60_000;
export const TTS_AUDIO_RETENTION_MS = 10 * 60_000;
export const settingsDir = Utils.paths.userData;
export const settingsPath = join(settingsDir, "settings.json");
export const defaultWorkspaceRoot = join(homedir(), "Documents", "BuddyWriter");
export const localAIRoot = join(Utils.paths.userData, "local-ai");
export const localAIBinDir = join(localAIRoot, "bin");
export const localAIPythonDir = join(localAIRoot, "python");
export const localAIVenvDir = join(localAIRoot, "venv");
export const localAIManifestsDir = join(localAIRoot, "manifests");
export const localAIModelsDir = join(localAIRoot, "models");
export const localAILogsDir = join(localAIRoot, "logs");
export const localAIHomeDir = join(localAIRoot, "home");
export const localAICacheDir = join(localAIRoot, "cache");
export const localAIHFDir = join(localAIRoot, "hf");
export const localAIHFHubDir = join(localAIHFDir, "hub");
export const localAIInstallStatePath = join(localAIManifestsDir, "install-state.json");
export const localAICachedCatalogPath = join(localAIManifestsDir, "catalog.json");
export const localAIDiagnosticsPath = join(localAIManifestsDir, "diagnostics.json");
export const localAIUVInstallerPath = join(localAIManifestsDir, "uv-install.sh");
export const tempDir = tmpdir();
